---
deployment:
  tasks:
    - export PATH=$HOME/venv/bin:$PATH
    - cd backendTryout
    - source ../venv/bin/activate   # kalau venv ada di root TryOut-Web
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
