# Generated by Django 5.2.6 on 2025-09-18 03:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='konten_materi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='slug_materi',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
