# Generated by Django 5.2.6 on 2025-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tryout_duration_totalrank_tryoutrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryout',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='tryout',
            name='duration',
            field=models.PositiveIntegerField(default=160),
        ),
    ]
