# Generated by Django 5.2.6 on 2025-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tryout_end_time_alter_tryout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryout',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
