# Generated by Django 5.2.6 on 2025-09-26 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tryout_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.BooleanField(default=False)),
                ('tryout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tryout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tryout')},
            },
        ),
    ]
