# Generated by Django 5.2.6 on 2025-09-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mission_profile_points_usermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='usermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='UserMission',
        ),
    ]
