# Generated by Django 5.2.6 on 2025-09-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_usermission_mission_remove_usermission_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
