# Generated by Django 5.2.6 on 2025-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_transaction_end_date_transaction_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
