# Generated by Django 5.2.6 on 2025-10-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profile_end_date_profile_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownUTBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUTBK', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('isi', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='code',
        ),
        migrations.AddField(
            model_name='discount',
            name='photo_promo',
            field=models.ImageField(blank=True, null=True, upload_to='promo/'),
        ),
    ]
