# Generated by Django 5.2.6 on 2025-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_countdownutbk_quote_remove_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='harga_bulan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
