# Generated by Django 5.2.6 on 2025-10-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_subscription_harga_bulan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='poster/')),
                ('photo', models.ImageField(upload_to='photo_event')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.IntegerField()),
                ('tempat', models.CharField()),
                ('syarat', models.TextField()),
            ],
        ),
    ]
