# Generated by Django 5.2.6 on 2025-10-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='penulis_materi',
        ),
    ]
